### ISSUE TITLE
Exe is not compatible

### ISSUE THREAD

**Issue by zergling-man** [nmbook/pidgin-libbnet#2]
First off, does this still get worked on? Latest commit a year ago...
Anyway. If you're still hanging around, help out a brain-addled overtired guy and answer this riddle: Windows 7 Home Premium 64-bit is complaining the exe is not compatible with it, re 32/64. I'm grabbing links to the exe (such as in the how-to) and going right-click -> save. Is this wrong? I can't find any other way of downloading from github.

**Comment by nmbook** [comment]
I'm not actively working on it. The reason is because of lack of apparent users (myself included since last month). I used this plugin on Windows 7 64-bit for a while before switching to using on on Linux and the only .exe is the installer (which copies the plugin to your Pidgin plugin folder). The installer itself doesn't do anything complicated and should be compatible with 32-bit and 64-bit Windows, so have you attempted to copy the plugin manually (everything inside of /dist/win32/in/ should be copied into C:\Program Files (x86)\Pidgin\; if done correctly there should be 2 dlls, and 3 unessential images)?

**Comment by zergling-man** [comment]
Oh, I found the problem. I don't know how to download files from Github. Apparently "save target as" doesn't work. I'll go fix that and the problem should be fixed.

**Comment by nmbook** [comment]
Okay.
